from PyQt6.QtWidgets import QMainWindow

class MainWindow(QMainWindow):
    def changeMedia(self, musicID: int) -> None: ...
    def play(self) -> None: ...

    def changePlaybackState(self) -> None: ...
    def changeRandom(self) -> None: ...
    def previousTrack(self) -> None: ...
    def nextTrack(self) -> None: ...
    def mute(self) -> None: ...
    def changeVolume(self, volume: float) -> None: ...
    def stopMedia(self) -> None: ...
    def setMediaPosition(self, value: int) -> None: ...
    def changeRepeat(self) -> None: ...